### ISSUE TITLE
复现时遇到下面的错误，请问怎么解决？

### ISSUE THREAD

**Issue by Shiyhm** [jhb86253817/PromptMRG#2]
Traceback (most recent call last):
  File "E:\Laboratory\project\Medical-Report-Genernate\PromptMRG\main_test.py", line 120, in <module>
    main()
  File "E:\Laboratory\project\Medical-Report-Genernate\PromptMRG\main_test.py", line 115, in main
    log = tester.test_blip()
  File "E:\Laboratory\project\Medical-Report-Genernate\PromptMRG\modules\tester.py", line 54, in test_blip
    reports, _, _ = self.model.generate(images, clip_memory, sample=False, num_beams=self.args.beam_size, max_length=self.args.gen_max_len, min_length=self.args.gen_min_len)
  File "E:\Laboratory\project\Medical-Report-Genernate\PromptMRG\models\blip.py", line 151, in generate
    outputs = self.text_decoder.generate(input_ids=input_ids,
  File "D:\ANACONDA\envs\torch-cp38\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\ANACONDA\envs\torch-cp38\lib\site-packages\transformers\generation\utils.py", line 1611, in generate
    return self.beam_search(
  File "D:\ANACONDA\envs\torch-cp38\lib\site-packages\transformers\generation\utils.py", line 2909, in beam_search
    outputs = self(
  File "D:\ANACONDA\envs\torch-cp38\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\ANACONDA\envs\torch-cp38\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Laboratory\project\Medical-Report-Genernate\PromptMRG\models\med.py", line 886, in forward
    outputs = self.bert(
  File "D:\ANACONDA\envs\torch-cp38\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\ANACONDA\envs\torch-cp38\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Laboratory\project\Medical-Report-Genernate\PromptMRG\models\med.py", line 781, in forward
    encoder_outputs = self.encoder(
  File "D:\ANACONDA\envs\torch-cp38\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\ANACONDA\envs\torch-cp38\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Laboratory\project\Medical-Report-Genernate\PromptMRG\models\med.py", line 445, in forward
    layer_outputs = layer_module(
  File "D:\ANACONDA\envs\torch-cp38\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\ANACONDA\envs\torch-cp38\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Laboratory\project\Medical-Report-Genernate\PromptMRG\models\med.py", line 361, in forward
    cross_attention_outputs = self.crossattention(
  File "D:\ANACONDA\envs\torch-cp38\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\ANACONDA\envs\torch-cp38\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Laboratory\project\Medical-Report-Genernate\PromptMRG\models\med.py", line 277, in forward
    self_outputs = self.self(
  File "D:\ANACONDA\envs\torch-cp38\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\ANACONDA\envs\torch-cp38\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Laboratory\project\Medical-Report-Genernate\PromptMRG\models\med.py", line 178, in forward
    attention_scores = torch.matmul(query_layer, key_layer.transpose(-1, -2))
RuntimeError: The size of tensor a (3) must match the size of tensor b (9) at non-singleton dimension 0

进程已结束,退出代码1

**Comment by Shiyhm** [comment]
解决方法参考这里https://github.com/salesforce/BLIP/issues/165
